-- ==========================================
-- COMBINED DATABASE SCRIPT - RENAME & SCHEMA
-- ==========================================
-- Run this in your Supabase SQL Editor to:
-- 1. Rename existing tables (preserving data)
-- 2. Create/update complete database schema

-- ==========================================
-- PART 1: TABLE RENAME SCRIPT - PRESERVE EXISTING DATA
-- ==========================================

-- 1. Rename existing tables if they exist
-- This will preserve all your existing data

-- Rename meetings table (if it exists and bcl_meetings_meetings doesn't exist)
DO $$
BEGIN
    -- Check if old meetings table exists and new one doesn't
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'meetings') 
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'bcl_meetings_meetings') THEN
        -- Rename the table
        ALTER TABLE meetings RENAME TO bcl_meetings_meetings;
        RAISE NOTICE 'Table "meetings" renamed to "bcl_meetings_meetings"';
    ELSE
        RAISE NOTICE 'Table rename skipped - either "meetings" doesn''t exist or "bcl_meetings_meetings" already exists';
    END IF;
END $$;

-- 2. Check if you have any existing system_settings or reminder_logs tables
-- and rename them if needed

DO $$
BEGIN
    -- Rename system_settings if it exists
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'system_settings') 
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'bcl_meetings_system_settings') THEN
        ALTER TABLE system_settings RENAME TO bcl_meetings_system_settings;
        RAISE NOTICE 'Table "system_settings" renamed to "bcl_meetings_system_settings"';
    END IF;

    -- Rename reminder_logs if it exists
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'reminder_logs') 
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'bcl_meetings_reminder_logs') THEN
        ALTER TABLE reminder_logs RENAME TO bcl_meetings_reminder_logs;
        RAISE NOTICE 'Table "reminder_logs" renamed to "bcl_meetings_reminder_logs"';
    END IF;
END $$;

-- ==========================================
-- PART 2: APPOINTMENT REMINDER SYSTEM DATABASE SCHEMA
-- ==========================================

-- 1. ENSURE MEETINGS TABLE EXISTS WITH PROPER STRUCTURE
-- Note: If renaming existing meetings table, it will have id_main as primary key
CREATE TABLE IF NOT EXISTS bcl_meetings_meetings (
    id_main BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_date TEXT,
    booking_day VARCHAR,
    meeting_date TEXT,
    meeting_day VARCHAR,
    meeting_type VARCHAR,
    meeting_venue_area VARCHAR,
    client_name VARCHAR,
    client_company VARCHAR,
    client_mobile VARCHAR,
    bcl_attendee VARCHAR,
    bcl_attendee_mobile VARCHAR,
    meeting_agenda TEXT,
    meeting_duration BIGINT,
    venue_distance BIGINT,
    meeting_start_time VARCHAR,
    meeting_end_time VARCHAR,
    meeting_slot_start_time VARCHAR,
    meeting_slot_end_time VARCHAR,
    status VARCHAR,
    google_event_id VARCHAR,
    google_meet_link TEXT,
    badge_status VARCHAR(20),
    -- Add additional columns for reminder system
    client_email TEXT,
    client_phone TEXT,
    venue TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TRACKING LOGS (Prevents duplicate messages)
CREATE TABLE IF NOT EXISTS bcl_meetings_reminder_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT REFERENCES bcl_meetings_meetings(id_main) ON DELETE CASCADE,
    reminder_type TEXT NOT NULL, -- 'morning_report', 'weekly_report', '1_hour', '5_min'
    sent_at TIMESTAMPTZ DEFAULT NOW(),
    recipient_group TEXT, -- 'admin', 'client'
    channel TEXT -- 'whatsapp', 'firebase'
);

-- 3. SYSTEM SETTINGS (Turn features ON/FALSE easily)
CREATE TABLE IF NOT EXISTS bcl_meetings_system_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    description TEXT
);

-- 4. INSERT DEFAULT SETTINGS (only if they don't exist)
INSERT INTO bcl_meetings_system_settings (key, value, description)
SELECT 
    'enable_morning_report', 'true', 'Send 6 AM daily summary'
WHERE NOT EXISTS (SELECT 1 FROM bcl_meetings_system_settings WHERE key = 'enable_morning_report');

INSERT INTO bcl_meetings_system_settings (key, value, description)
SELECT 
    'enable_weekly_report', 'true', 'Send Friday evening summary'
WHERE NOT EXISTS (SELECT 1 FROM bcl_meetings_system_settings WHERE key = 'enable_weekly_report');

INSERT INTO bcl_meetings_system_settings (key, value, description)
SELECT 
    'enable_1hr_reminder', 'true', 'Send reminder 1 hour before meeting'
WHERE NOT EXISTS (SELECT 1 FROM bcl_meetings_system_settings WHERE key = 'enable_1hr_reminder');

INSERT INTO bcl_meetings_system_settings (key, value, description)
SELECT 
    'enable_5min_reminder', 'true', 'Send reminder 5 minutes before meeting'
WHERE NOT EXISTS (SELECT 1 FROM bcl_meetings_system_settings WHERE key = 'enable_5min_reminder');

INSERT INTO bcl_meetings_system_settings (key, value, description)
SELECT 
    'admin_whatsapp_group_code', 'FnIcpmLqutDBOCJwZAC6Wn', 'Invite code for Admin Group'
WHERE NOT EXISTS (SELECT 1 FROM bcl_meetings_system_settings WHERE key = 'admin_whatsapp_group_code');

INSERT INTO bcl_meetings_system_settings (key, value, description)
SELECT 
    'whatsapp_instance_name', 'BCL REMINDERS', 'Evolution API Instance Name'
WHERE NOT EXISTS (SELECT 1 FROM bcl_meetings_system_settings WHERE key = 'whatsapp_instance_name');

INSERT INTO bcl_meetings_system_settings (key, value, description)
SELECT 
    'whatsapp_api_key', 'b4dfe130f8a7f80eee25e09e1e872ab0', 'Evolution API Key'
WHERE NOT EXISTS (SELECT 1 FROM bcl_meetings_system_settings WHERE key = 'whatsapp_api_key');

INSERT INTO bcl_meetings_system_settings (key, value, description)
SELECT 
    'whatsapp_base_url', 'https://evolution-api-production-15f8.up.railway.app', 'Evolution API URL'
WHERE NOT EXISTS (SELECT 1 FROM bcl_meetings_system_settings WHERE key = 'whatsapp_base_url');

INSERT INTO bcl_meetings_system_settings (key, value, description)
SELECT 
    'firebase_project_id', 'bcl-meetings', 'Firebase Project ID'
WHERE NOT EXISTS (SELECT 1 FROM bcl_meetings_system_settings WHERE key = 'firebase_project_id');

-- 5. CREATE INDEXES FOR BETTER PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_bcl_meetings_reminder_logs_meeting_id ON bcl_meetings_reminder_logs(meeting_id);
CREATE INDEX IF NOT EXISTS idx_bcl_meetings_reminder_logs_type_sent ON bcl_meetings_reminder_logs(reminder_type, sent_at);
CREATE INDEX IF NOT EXISTS idx_bcl_meetings_meetings_start_time ON bcl_meetings_meetings(meeting_start_time);
CREATE INDEX IF NOT EXISTS idx_bcl_meetings_meetings_date ON bcl_meetings_meetings(meeting_date);

-- 6. ENABLE NECESSARY EXTENSIONS FOR CRON JOBS
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

-- ==========================================
-- PART 3: VERIFICATION & DATA INTEGRITY CHECKS
-- ==========================================

-- 7. Verify the rename worked and all tables exist
SELECT 
    table_name,
    table_type 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name LIKE 'bcl_meetings_%'
ORDER BY table_name;

-- 8. Check data integrity
SELECT 
    'bcl_meetings_meetings' as table_name,
    COUNT(*) as record_count
FROM bcl_meetings_meetings
UNION ALL
SELECT 
    'bcl_meetings_system_settings' as table_name,
    COUNT(*) as record_count  
FROM bcl_meetings_system_settings
UNION ALL
SELECT 
    'bcl_meetings_reminder_logs' as table_name,
    COUNT(*) as record_count
FROM bcl_meetings_reminder_logs;

-- 9. Verify system settings are properly configured
SELECT key, value, description
FROM bcl_meetings_system_settings
ORDER BY key;
